# for devcontainer
services:
  dotnet_app:
    build:
      target: devcontainers
      context: ./
      dockerfile: Dockerfile
    image: dotnet_img_devcontainer:latest
    container_name: dotnet_container_devcontainer
    volumes:
      - ./:/app
